# Generated by Django 5.2.11 on 2026-02-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordemservico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.produto', verbose_name='Peça/Produto'),
        ),
    ]
