# Generated by Django 5.2.11 on 2026-04-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_itemordemservico_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
